
package org.mgnl.nicki.vaadin.base.components;

/*-
 * #%L
 * nicki-vaadin-base
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.mgnl.nicki.core.thread.NickiProgress;
import org.mgnl.nicki.core.thread.ProgressRunner;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.ProgressBar;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class NickiProgressComponent extends CustomComponent implements NickiProgress {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label details;
	@AutoGenerated
	private Label progressLabel;
	@AutoGenerated
	private ProgressBar progress;
	@AutoGenerated
	private Label title;

	private int count;
	private int current;
	
	private List<FinishedListener> finishedListeners;


	public void init(ProgressRunner runner) {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		count = runner.getCount();
		title.setValue(runner.getTitle());
		progressed(0, "");
        UI.getCurrent().setPollInterval(500);

	}

	public void progressed(int newCurrent, String newDetails) {
		this.current = newCurrent;
		float value = new Float(current) / count;
		progress.setValue(value);
		details.setValue(newDetails);
		if (StringUtils.isNotBlank(newDetails)) {
			Notification.show(newDetails, Type.TRAY_NOTIFICATION);
		}
		if (current < count)
			progressLabel.setValue("" + ((int) (value * 100)) + "% ("+ current + "/" + count + ")");
		else
			progressLabel.setValue("finished");
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		// title
		title = new Label();
		title.setWidth("-1px");
		title.setHeight("-1px");
		title.setValue("title");
		mainLayout.addComponent(title);
		mainLayout.setComponentAlignment(title, new Alignment(20));

		// progress
		progress = new ProgressBar();
		progress.setWidth("-1px");
		progress.setHeight("-1px");
		mainLayout.addComponent(progress);
		mainLayout.setComponentAlignment(progress, new Alignment(20));

		// progressLabel
		progressLabel = new Label();
		progressLabel.setWidth("-1px");
		progressLabel.setHeight("-1px");
		progressLabel.setValue("Label");
		mainLayout.addComponent(progressLabel);
		mainLayout.setComponentAlignment(progressLabel, new Alignment(20));

		// details
		details = new Label();
		details.setWidth("-1px");
		details.setHeight("-1px");
		details.setValue("Details");
		mainLayout.addComponent(details);
		mainLayout.setComponentAlignment(details, new Alignment(20));

		return mainLayout;
	}

	public void finish() {
        // Update the UI thread-safely
        UI.getCurrent().access(() -> {
                // Stop polling
                UI.getCurrent().setPollInterval(-1);
                progress.setEnabled(false);
                setVisible(false);
        });
        if (finishedListeners != null) {
        	for (FinishedListener finishedListener : finishedListeners) {
				finishedListener.finished();
			}
        }
	}

	public void addFinishedListener(FinishedListener finishedListener) {
		if (this.finishedListeners == null) {
			this.finishedListeners = new ArrayList<>();
		}
		this.finishedListeners.add(finishedListener);
	}

}
