
package org.mgnl.nicki.vaadin.base.components;

/*-
 * #%L
 * nicki-vaadin-base
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.vaadin.base.application.NickiApplication;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

@SuppressWarnings("serial")
public class WelcomeDialog extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Button logout;
	@AutoGenerated
	private Label space;
	@AutoGenerated
	private Label hello;
	
	private NickiApplication application;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public WelcomeDialog(NickiApplication app) {
		this.application = app;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		hello.setValue(I18n.getText("nicki.application.greeting", application.getNickiContext().getUser().getDisplayName()));
		logout.setCaption(I18n.getText("nicki.application.logout"));
		logout.addClickListener(event -> application.logout());
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		//horizontalLayout_1.setWidth("1000px");
		//horizontalLayout_1.setHeight("100px");
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		
		// hello
		hello = new Label();
		hello.setWidth("-1px");
		hello.setHeight("-1px");
		hello.setValue("Hello");
		hello.setImmediate(false);
		mainLayout.addComponent(hello);
		mainLayout.setComponentAlignment(hello, new Alignment(33));
		
		// space
		space = new Label();
		space.setWidth("10px");
		space.setHeight("-1px");
		space.setImmediate(false);
		mainLayout.addComponent(space);
		
		// logout
		logout = new Button();
		logout.setWidth("-1px");
		logout.setHeight("-1px");
		logout.setImmediate(false);
		mainLayout.addComponent(logout);
		
		return mainLayout;
	}

}
