
package org.mgnl.nicki.editor.projects.members;

/*-
 * #%L
 * nicki-editor-projects
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import org.mgnl.nicki.editor.projects.objects.Directory;
import org.mgnl.nicki.editor.projects.objects.Member;
import org.mgnl.nicki.editor.projects.objects.Member.RIGHT;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.VerticalLayout;


@SuppressWarnings("serial")
public class DirectoryComponent extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private RadioButtonGroup<Member.RIGHT> rights;
	@AutoGenerated
	private Label directoryLabel;

	private Directory directory;
	private Member member;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DirectoryComponent(Member target, Directory dir) {
		this.member = target;
		this.directory = dir;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		directoryLabel.setValue(this.directory.getDisplayName());
		rights.setItems(RIGHT.values());
		rights.setItemCaptionGenerator(RIGHT::name);
		
		if (member.hasReadRight(directory)) {
			rights.setSelectedItem(Member.RIGHT.READ);
		} else if (member.hasWriteRight(directory)) {
				rights.setSelectedItem(Member.RIGHT.WRITE);
		} else {
			rights.setSelectedItem(Member.RIGHT.NONE);
		}
		rights.setStyleName("horizontal");
	}

	public void save() {
		member.setRight(directory, (RIGHT) rights.getValue());
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout
				.addComponent(horizontalLayout_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("100.0%");
		horizontalLayout_1.setMargin(false);
		
		// directoryLabel
		directoryLabel = new Label();
		directoryLabel.setWidth("200px");
		directoryLabel.setHeight("-1px");
		directoryLabel.setValue("Verzeichnis");
		horizontalLayout_1.addComponent(directoryLabel);
		
		// rights
		rights = new RadioButtonGroup<Member.RIGHT>();
		rights.setWidth("-1px");
		rights.setHeight("-1px");
		horizontalLayout_1.addComponent(rights);
		
		return horizontalLayout_1;
	}

}
