
package org.mgnl.nicki.vaadin.base.editor;

/*-
 * #%L
 * nicki-vaadin-base
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;

import org.mgnl.nicki.core.context.NickiContext;
import org.mgnl.nicki.core.data.TreeData;
import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.core.objects.DynamicObject;
import org.mgnl.nicki.core.util.XMLImporter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Upload.FailedEvent;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Window;

public class ImportTreeAction extends BaseTreeAction implements  Upload.SucceededListener,
		Upload.FailedListener, Upload.Receiver {

	private static final long serialVersionUID = 8567493886374796976L;


	private AbsoluteLayout mainLayout;
	private HorizontalLayout horizontalLayout_1;
	private Upload importComponent;
	private ByteArrayOutputStream outputStream;
	private Window previewWindow;
	private NickiContext context;
	private String i18nBase;
	private TreeData dynamicObject;
	private TreeEditor treeEditor;


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public ImportTreeAction(TreeEditor treeEditor, Class<? extends DynamicObject> classDefinition,
			String name, String i18nBase) {
		super(classDefinition, name, null);
		this.treeEditor = treeEditor;
		this.context = treeEditor.getNickiContext();
		this.i18nBase = i18nBase;
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	public void execute(TreeData dynamicObject) {
		this.dynamicObject = dynamicObject;
		
		importComponent.setCaption(I18n.getText(i18nBase + ".import.caption"));
		importComponent.setButtonCaption(I18n.getText(i18nBase + ".import.button.caption"));
		importComponent.addSucceededListener((Upload.SucceededListener) this);
		importComponent.addFailedListener((Upload.FailedListener) this);

		if (null != this.getParent()) {
			this.setParent(null);
		}
		previewWindow = new Window(I18n.getText(i18nBase + ".import.window.title"), this);
		previewWindow.setModal(true);
		previewWindow.setWidth(1024, Unit.PIXELS);
		previewWindow.setHeight(520, Unit.PIXELS);
		UI.getCurrent().addWindow(previewWindow);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(true);
		horizontalLayout_1.setSpacing(true);
		
		// exportElement
		importComponent = new Upload("Importieren", this);
		importComponent.setCaption("Importieren");
		importComponent.setWidth("-1px");
		importComponent.setHeight("-1px");
		horizontalLayout_1.addComponent(importComponent);
		
		return horizontalLayout_1;
	}

	public void close() {
		UI.getCurrent().removeWindow(previewWindow);
	}

	public OutputStream receiveUpload(String filename, String mimeType) {
		this.outputStream = new ByteArrayOutputStream();
		return this.outputStream;
	}

	public void uploadFailed(FailedEvent event) {
		this.outputStream = null;
		Notification.show("Import failed", "Importing "
                + event.getFilename() + " of type '"
                + event.getMIMEType() + "' failed.", Notification.Type.ERROR_MESSAGE);
	}

	public void uploadSucceeded(SucceededEvent event) {
		try {
			XMLImporter importer = new XMLImporter(context, dynamicObject.getPath(), new ByteArrayInputStream(outputStream.toByteArray()));
			importer.create();
			treeEditor.refresh(dynamicObject);
			Notification.show("Import successful", Notification.Type.HUMANIZED_MESSAGE);
		} catch (Exception e) {
			Notification.show("Import failed", "Importing "
	                + event.getFilename() + " of type '"
	                + event.getMIMEType() + "' failed.", Notification.Type.ERROR_MESSAGE);
		}
	}

}
