
package org.mgnl.nicki.shop.core;

/*-
 * #%L
 * nicki-shop
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import org.mgnl.nicki.shop.base.inventory.Inventory;
import org.mgnl.nicki.shop.base.objects.Cart;
import org.mgnl.nicki.shop.base.objects.Cart.CART_STATUS;
import org.mgnl.nicki.shop.base.objects.CartEntry;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.v7.data.Item;
import com.vaadin.ui.CustomComponent;
import com.vaadin.v7.ui.Label;
import com.vaadin.v7.ui.Table;
import com.vaadin.v7.ui.VerticalLayout;

public class CartViewer extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table cartEntries;
	@AutoGenerated
	private Label recipient;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	private static final long serialVersionUID = 8441664095916322794L;
	private Cart cart;
	private Inventory inventory;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CartViewer(Cart cart) {
		this.cart = cart;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.recipient.setValue(this.cart.getRecipient().getDisplayName());
		fillCartEntries();
	}

	public CartViewer(Inventory inventory) {
		this.inventory = inventory;
		this.cart = inventory.getCart("SHOP", CART_STATUS.NEW);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		this.recipient.setValue(this.inventory.getPerson().getDisplayName());
		fillCartEntries();
	}

	@SuppressWarnings("unchecked")
	private void fillCartEntries() {

		cartEntries.addContainerProperty("action", String.class, "");
		cartEntries.setColumnWidth("action", 50);
		cartEntries.setColumnHeader("action", "Aktion");
		cartEntries.addContainerProperty("right", String.class, "");
		cartEntries.setColumnWidth("right", -1);
		cartEntries.setColumnHeader("right", "Artikel");
		/*
		cartEntries.addContainerProperty("start", String.class, "");
		cartEntries.setColumnWidth("start", 70);
		cartEntries.setColumnHeader("start", I18n.getText(CatalogArticle.CAPTION_START));
		cartEntries.addContainerProperty("end", String.class, "");
		cartEntries.setColumnWidth("end", 70);
		cartEntries.setColumnHeader("end", I18n.getText(CatalogArticle.CAPTION_END));

		cartEntries.addContainerProperty("attributes", String.class, "");
		cartEntries.setColumnWidth("attributes", 420);
		cartEntries.setColumnHeader("attributes", "attributes");
		*/
		for (CartEntry cartEntry : cart.getCartEntries()) {
			Item item = cartEntries.addItem(cartEntry);
			item.getItemProperty("right").setValue(cartEntry.getDisplayName());
			item.getItemProperty("action").setValue(cartEntry.getAction().toString());
			/*
			if (cartEntry.getStart() != null) {
				item.getItemProperty("start").setValue(DataHelper.formatDisplayDay.format(cartEntry.getStart()));
			}
			if (cartEntry.getEnd() != null) {
				item.getItemProperty("end").setValue(DataHelper.formatDisplayDay.format(cartEntry.getEnd()));
			}
			item.getItemProperty("attributes").setValue(cartEntry.getAttributes().toString());
			*/
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// recipient
		recipient = new Label();
		recipient.setCaption("Empfänger");
		recipient.setWidth("-1px");
		recipient.setHeight("-1px");
		recipient.setValue("recipient");
		mainLayout.addComponent(recipient);
		
		// cartEntries
		cartEntries = new Table();
		cartEntries.setWidth("100.0%");
		cartEntries.setHeight("100.0%");
		mainLayout.addComponent(cartEntries);
		mainLayout.setExpandRatio(cartEntries, 1.0f);
		
		return mainLayout;
	}

}
