
package org.mgnl.nicki.vaadin.base.dialog;

/*-
 * #%L
 * nicki-vaadin-base
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.apache.commons.lang.StringUtils;
import org.mgnl.nicki.core.config.Config;
import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.dynamic.objects.objects.Person;
import org.mgnl.nicki.vaadin.base.application.AccessGroup;
import org.mgnl.nicki.vaadin.base.application.AccessGroupEvaluator;
import org.mgnl.nicki.vaadin.base.application.AccessRole;
import org.mgnl.nicki.vaadin.base.application.AccessRoleEvaluator;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Notification;
import com.vaadin.ui.VerticalLayout;

import lombok.extern.slf4j.Slf4j;

import com.vaadin.ui.Notification.Type;

@Slf4j
public class MainView extends CustomComponent implements NavigationSelector {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalSplitPanel hsplit;
	@AutoGenerated
	private Navigation navigation;
	private View activeView;;
	private List<NavigationFolder> navigationFolders = new ArrayList<NavigationFolder>();
	private Person user;

	private static final long serialVersionUID = 8701670605362637395L;
	public MainView(Person user) {
		this.user = user;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		hsplit.setSplitPosition(250, Unit.PIXELS);
		navigation = new TableNavigation(this);
		hsplit.setFirstComponent(navigation);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// hsplit
		hsplit = buildHsplit();
		mainLayout.addComponent(hsplit);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHsplit() {
		// common part: create layout
		hsplit = new HorizontalSplitPanel();
		hsplit.setImmediate(false);
		hsplit.setWidth("100.0%");
		hsplit.setHeight("100.0%");
		
		return hsplit;
	}

	public boolean show(NavigationEntry entry) {
		
		// TODO check is navigation change is allowed
		if (activeView != null && activeView.isModified()) {
			Notification.show(I18n.getText("nicki.navigation.message.modified"), Type.HUMANIZED_MESSAGE);
			return false;
		}
		View view = entry.getView();
		showView(view);
		return true;
	}

	public void showView(View view) {
		setActiveView(view);
		view.init();
		hsplit.setSecondComponent(view);
	}

	public View getActiveView() {
		return activeView;
	}

	public void setActiveView(View activeView) {
		this.activeView = activeView;
	}

	public void addNavigationEntry(String labelCaption, String caption, View view) {
		if (isAllowed(view.getClass())) {
			NavigationFolder folder= getNavigationFolder(labelCaption);
			NavigationEntry entry = new NavigationEntry(caption, view);
			folder.addEntry(entry);
		}
	}

	public void addNavigationSeparator() {

		NavigationFolder folder= new NavigationFolder();
		navigationFolders.add(folder);
	}

	private NavigationFolder getNavigationFolder(String caption) {
		for (NavigationFolder folder : navigationFolders) {
			if (!folder.isSeparator() && StringUtils.equals(caption, folder.getLabel().getCaption())) {
				return folder;
			}
		}
		NavigationLabel label = new NavigationLabel(caption);
		NavigationFolder folder = new NavigationFolder(label);
		navigationFolders.add(folder);
		return folder;
	}

	public void initNavigation() {
		navigation.init(navigationFolders);
	}
	

	private boolean isAllowed(Class<?> clazz) {
		boolean allowed = false;
		AccessRole roleAnnotation = clazz.getAnnotation(AccessRole.class);
		AccessGroup groupAnnotation = clazz.getAnnotation(AccessGroup.class);
		if (roleAnnotation == null && groupAnnotation == null) {
			allowed =  true;
		} else if (roleAnnotation != null){
			try {
				AccessRoleEvaluator roleEvaluator = roleAnnotation.evaluator().newInstance();
				allowed = roleEvaluator.hasRole(user, roleAnnotation.name());
				allowed |= roleEvaluator.hasRole(user, Config.getStringValues(roleAnnotation.configName()));
			} catch (Exception e) {
				log.error("Could not create AccessRoleEvaluator", e);
				allowed = false;
			}
		}
		if (!allowed && groupAnnotation != null) {
			try {
				AccessGroupEvaluator groupEvaluator = groupAnnotation.evaluator().newInstance();
				allowed = groupEvaluator.isMemberOf( user, groupAnnotation.name());
				if (groupAnnotation.configName() != null && groupAnnotation.configName().length > 0) {
					allowed |= groupEvaluator.isMemberOf(user, Config.getStringValues(groupAnnotation.configName()));
				}
			} catch (Exception e) {
				log.error("Could not create AccessGroupEvaluator", e);
				allowed = false;
			}
		}
		if (!allowed) {
			StringBuilder errorMsg = new StringBuilder();
			errorMsg.append(user.getDisplayName()).append(" tried to access application ");
			errorMsg.append(clazz.getName()).append(". Allowed: ");
			if (roleAnnotation != null) {
				errorMsg.append("Role: ").append(Arrays.toString(roleAnnotation.name()));
			}
			if (groupAnnotation != null) {
				if (errorMsg.length() > 0) {
					errorMsg.append(", ");
				}
				errorMsg.append("Group: ").append(Arrays.toString(groupAnnotation.name()));
			}
			log.debug(errorMsg.toString());
		}
		return allowed;
	}
}
