
package org.mgnl.nicki.editor.projects.directories;

/*-
 * #%L
 * nicki-editor-projects
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import org.mgnl.nicki.core.i18n.I18n;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.TextField;

@SuppressWarnings("serial")
public class NewDirectory extends VerticalLayout {
	private Button closeButton;

	
	private Button createButton;

	
	private TextField directory;

	
	private Label headline;

	NewDirectoryHandler newDirectoryHandler;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public NewDirectory(NewDirectoryHandler handler) {
		this.newDirectoryHandler = handler;
		buildMainLayout();

		directory.focus();
		applyI18n();
		
		createButton.addClickListener(event -> newDirectoryHandler.createNewDirectory((String) directory.getValue()));		
		closeButton.addClickListener(event -> newDirectoryHandler.closeNewDirectoryWindow());
	}

	private void applyI18n() {
		headline.setText(I18n.getText("nicki.editor.project.newdirectory.headline"));
		createButton.setText(I18n.getText("nicki.editor.project.newdirectory.button.create"));
		closeButton.setText(I18n.getText("nicki.editor.project.newdirectory.button.close"));
	}
		
	
	private void buildMainLayout() {		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// headline
		headline = new Label();
		headline.setWidth("400px");
		headline.setHeight("-1px");
		headline.setText("Headline");
		add(headline);
		
		// directory
		directory = new TextField();
		directory.setWidth("-1px");
		directory.setHeight("-1px");
		add(directory);
		
		// createButton
		createButton = new Button();
		createButton.setWidth("-1px");
		createButton.setHeight("-1px");
		createButton.setText("Create");
		add(createButton);
		
		// closeButton
		closeButton = new Button();
		closeButton.setWidth("-1px");
		closeButton.setHeight("-1px");
		closeButton.setText("Close");
		add(closeButton);
	}

}
