
package org.mgnl.nicki.editor.catalogs;

/*-
 * #%L
 * nicki-editor-catalogs
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import org.mgnl.nicki.core.data.TreeData;
import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.core.objects.DynamicObjectException;
import org.mgnl.nicki.shop.base.objects.CatalogPage;
import org.mgnl.nicki.vaadin.base.components.EnterNameDialog;
import org.mgnl.nicki.vaadin.base.components.EnterNameHandler;
import org.mgnl.nicki.vaadin.base.editor.ClassEditor;
import org.mgnl.nicki.vaadin.base.editor.NickiTreeEditor;
import org.mgnl.nicki.vaadin.base.helper.UIHelper;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.v7.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class CatalogPageViewer extends CustomComponent implements ClassEditor {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button saveButton;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button deleteAttributeButton;
	@AutoGenerated
	private Button newAttributeButton;
	@AutoGenerated
	private Table attributes;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button deleteCategoryButton;
	@AutoGenerated
	private Button newCategoryButton;
	@AutoGenerated
	private Table categories;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private CatalogPage page;

	public CatalogPageViewer() {
	}

	public void setDynamicObject(NickiTreeEditor nickiEditor,
			TreeData dynamicObject) {
		this.page = (CatalogPage) dynamicObject;
		buildMainLayout();
		setCompositionRoot(mainLayout);

		initCategories();
		initAttributes();

	}

	private void initCategories() {
		categories.setSelectable(true);
		categories.addContainerProperty("category", String.class, null);
		if (page.hasCategories()) {
			for (String value : page.getCategories()) {
				categories.addItem(new Object[] { value }, value);
			}
		}
		newCategoryButton.addClickListener(event -> addEntry(categories));
		deleteCategoryButton.addClickListener(event -> deleteEntry(categories));
	}

	protected void deleteEntry(Table table) {
		if (table.getValue() != null) {
			table.removeItem(table.getValue());
		}
	}

	protected void addEntry(Table table) {
		EnterNameHandler handler = new NewEntryEnterNameHandler(table);
		EnterNameDialog dialog = new EnterNameDialog(
				"nicki.editor.catalogs.entry.new", I18n.getText("nicki.editor.catalogs.entry.new.window.title"));
		dialog.setHandler(handler);
		dialog.setWidth(440, Unit.PIXELS);
		dialog.setHeight(500, Unit.PIXELS);
		dialog.setModal(true);
		UI.getCurrent().addWindow(dialog);
	}

	private void initAttributes() {
		attributes.setSelectable(true);
		attributes.addContainerProperty("attribute", String.class, null);
		if (page.hasAttributes()) {
			for (String value : page.getCategories()) {
				attributes.addItem(new Object[] { value }, value);
			}
		}
		newAttributeButton.addClickListener(event -> addEntry(attributes));
		deleteAttributeButton.addClickListener(event ->	deleteEntry(attributes));
	}

	@Override
	public void save() throws DynamicObjectException {
		if (this.page.isNew()) {
			this.page.create();
		} else {
			Notification.show(
					"Object changed: " + this.page.isModified());
			this.page.update();
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		mainLayout.addComponent(horizontalLayout_2);
		
		// saveButton
		saveButton = new Button();
		saveButton.setCaption("Speichern");
		UIHelper.setImmediate(saveButton, true);
		saveButton.setWidth("-1px");
		saveButton.setHeight("-1px");
		mainLayout.addComponent(saveButton);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// categories
		categories = new Table();
		categories.setCaption("Kategorien");
		categories.setWidth("400px");
		categories.setHeight("120px");
		horizontalLayout_1.addComponent(categories);
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		horizontalLayout_1.addComponent(verticalLayout_1);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setWidth("-1px");
		verticalLayout_1.setHeight("-1px");
		verticalLayout_1.setMargin(true);
		verticalLayout_1.setSpacing(true);
		
		// newCategoryButton
		newCategoryButton = new Button();
		newCategoryButton.setCaption("Neu");
		UIHelper.setImmediate(newCategoryButton, true);
		newCategoryButton.setWidth("-1px");
		newCategoryButton.setHeight("-1px");
		verticalLayout_1.addComponent(newCategoryButton);
		
		// deleteCategoryButton
		deleteCategoryButton = new Button();
		deleteCategoryButton.setCaption("Löschen");
		UIHelper.setImmediate(deleteCategoryButton, true);
		deleteCategoryButton.setWidth("-1px");
		deleteCategoryButton.setHeight("-1px");
		verticalLayout_1.addComponent(deleteCategoryButton);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// attributes
		attributes = new Table();
		attributes.setCaption("Attribute");
		attributes.setWidth("400px");
		attributes.setHeight("120px");
		horizontalLayout_2.addComponent(attributes);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		horizontalLayout_2.addComponent(verticalLayout_2);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// newAttributeButton
		newAttributeButton = new Button();
		newAttributeButton.setCaption("Neu");
		UIHelper.setImmediate(newAttributeButton, true);
		newAttributeButton.setWidth("-1px");
		newAttributeButton.setHeight("-1px");
		verticalLayout_2.addComponent(newAttributeButton);
		
		// deleteAttributeButton
		deleteAttributeButton = new Button();
		deleteAttributeButton.setCaption("Löschen");
		UIHelper.setImmediate(deleteAttributeButton, true);
		deleteAttributeButton.setWidth("-1px");
		deleteAttributeButton.setHeight("-1px");
		verticalLayout_2.addComponent(deleteAttributeButton);
		
		return verticalLayout_2;
	}
}
