
package org.mgnl.nicki.shop.rules;

/*-
 * #%L
 * nicki-shop
 * %%
 * Copyright (C) 2017 Ralf Hirning
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */


import java.util.List;

import org.mgnl.nicki.core.config.Config;
import org.mgnl.nicki.core.i18n.I18n;
import org.mgnl.nicki.core.util.Classes;
import org.mgnl.nicki.core.objects.DynamicObject;
import org.mgnl.nicki.shop.base.objects.Selector;
import org.mgnl.nicki.vaadin.base.components.DialogBase;
import org.mgnl.nicki.vaadin.base.helper.UIHelper;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Component;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;

import lombok.extern.slf4j.Slf4j;


@Slf4j
@SuppressWarnings("serial")
public class RuleEditor extends DialogBase {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Button addButton;
	@AutoGenerated
	private Component value;
	@AutoGenerated
	private NativeSelect<Selector> selector;
	
	private ValueProviderComponent valueProvider;
	
	private RuleAttributeField.RuleHandler ruleHandler;
	
	private DynamicObject dynamicObject;
	private String i18nBase;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RuleEditor(DynamicObject dynamicObject, String i18nBase, String title) {
		super(title);
		this.dynamicObject = dynamicObject;
		this.i18nBase = i18nBase;
		buildMainLayout();
		initI18n();
		setCompositionRoot(mainLayout);
		initSelector();
		addButton.addClickListener(event -> {
				if (getValue() != null) {
					ruleHandler.setRule((Selector) selector.getValue(), getValue());
					close();
				}
		});
	}


	private void initI18n() {
		selector.setCaption(I18n.getText(i18nBase + ".selector.title"));
		addButton.setCaption(I18n.getText(i18nBase + ".addbutton.title"));
	}


	protected String getValue() {
		return valueProvider.getValue();
	}


	private void initSelector() {
		selector.addValueChangeListener(event -> initValues(event.getValue()));
		selector.setEmptySelectionAllowed(false);
		List<Selector> selectorList = 
			this.dynamicObject.getContext().loadChildObjects(Selector.class, Config.getString("nicki.selectors.basedn"),
					null);
		selector.setItems(selectorList);
		if (selectorList != null && selectorList.size() > 0) {
			selector.setSelectedItem(selectorList.get(0));
		}
	}

	protected void initValues(Selector selectedSelector) {
		if (value != null) {
			mainLayout.removeComponent(value);
			value = null;
		}
		valueProvider = null;
		if (selectedSelector.hasValueProvider()) {
			try {
				valueProvider = getValueProvider(selectedSelector);
			} catch (Exception e) {
				valueProvider = null;
				log.error("Error", e);
			} 
		}
	
		if (this.valueProvider == null) {
			valueProvider = new ListValueProvider();
		}
		valueProvider.init(selectedSelector, this.i18nBase);
		value = valueProvider.getValueList();
		mainLayout.addComponent(value);
		
	}


	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// selector
		selector = new NativeSelect<>();
		selector.setCaption("Merkmal");
		UIHelper.setImmediate(selector, true);
		selector.setWidth("200px");
		selector.setHeight("-1px");
		mainLayout.addComponent(selector);
		
		// addButton
		addButton = new Button();
		addButton.setCaption("Add");
		addButton.setWidth("-1px");
		addButton.setHeight("-1px");
		mainLayout.addComponent(addButton);
		
		return mainLayout;
	}


	public void setHandler(RuleAttributeField.RuleHandler ruleHandler) {
		this.ruleHandler = ruleHandler;
	}
	
	public ValueProviderComponent getValueProvider(Selector selector) throws InstantiationException, IllegalAccessException, ClassNotFoundException {
		return (ValueProviderComponent) Classes.newInstance((String) selector.getValueProviderClass());
	};


}
